name: instrument_tuner
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  desktop_window: ^0.4.0
  flutter:
    sdk: flutter
  flutter_audio_capture: ^1.1.1
  flutter_localizations:
    sdk: flutter
  pitch_detector_dart: ^0.0.2
  pitchupdart: ^0.0.2
  syncfusion_flutter_gauges: ^22.2.7
  syncfusion_localizations: ^22.2.7
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

#  assets:
#    # Add assets from the images directory to the application.
#    - assets/images/
